name: Docs

on:
  push:
    branches:
      - main

jobs:
  Docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ secrets.REPO_TOKEN }}

    - name: Install Dependencies
      working-directory: docs
      run: pip install -r requirements.txt

    - name: Build Docs
      working-directory: .
      run: |
        sphinx-apidoc -o apidoc/ ../TenshiTranslator --separate
        make html
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        publish_dir: './docs/build/html'